config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes do
   resources :comments, only: [:create, :edit, :update, :destroy]
  end
  
  root "recipes#index"
  get 'profile/user_page'
  
  get "your_recipes" => "recipes#your_recipes"
  get "user_recipes" => "recipes#user_recipes"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :recipe
	belongs_to :user
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


    has_many :comments
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :recipe
  has_many :recipes
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

	  protected

	 	def configure_permitted_parameters
	 		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :birthday])
	 		devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :birthday])
	 	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    respond_to do |format|
      if @comment.save
        format.html{redirect_to recipe_path(@comment.recipe_id), notice: 'Comment was successfully created.'}
      else
        format.html { redirect_to recipe_path}
      end
    end
  end
  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @comment = Comment.find(params[:id])
  end
  def update
    @comment = Comment.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.html{redirect_to recipe_path(@comment.recipe_id), notice: 'Comment was successfully created.'}
      else
        format.html { redirect_to recipe_path}
      end
    end
  end
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to recipe_path(@comment.recipe), notice: 'Comment was successfully destroyed.' }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :comment_entry, :recipe_id, :user_id, :rating)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @comment = Comment.new
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def your_recipes
  end

  def user_recipes
    @user = User.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :ingredients, :author, :category, :directions, :notes, :user_id, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/comments/_form.html.erb
<%= form_for([@recipe, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

  <% end %>



    <script>
      $(document).ready(function(){
          $("#btn1").hover(function(){
              $("#comment_rating").val("1");
          });
          $("#btn2").hover(function(){
              $("#comment_rating").val("2");
          });
      
          $("#btn3").hover(function(){
              $("#comment_rating").val("3");
          });
          $("#btn4").hover(function(){
              $("#comment_rating").val("4");
          });
          $("#btn5").hover(function(){
              $("#comment_rating").val("5");
          });
      });
    </script>


  <div id="rating">
    <strong>Rate it:</strong>
    <div class="glyphicon glyphicon-star-empty" id="btn1"></div>
    <div class="glyphicon glyphicon-star-empty" id="btn2"></div>
    <div class="glyphicon glyphicon-star-empty" id="btn3"></div>
    <div class="glyphicon glyphicon-star-empty" id="btn4"></div>
    <div class="glyphicon glyphicon-star-empty" id="btn5"></div>
    <%= f.text_field :rating, size:"1", class:"no-lines" %>
  </div>

  <div class="form-group">
    <%= f.label :comment_entry, class:"sr-only" %><br>
    <%= f.text_area :comment_entry, class: "form-control", placeholder: "Comment", rows: 5 %>
  </div>
  <div class="form-group">
    <%= f.label :user_id, class:"sr-only" %><br>
    <%= f.text_field :user_id, class: "form-control", placeholder: "Author" %>
  </div>
  
    <div class="cant-see-me">
    <%= f.number_field :recipe_id, value: @recipe.id %>
    <%= f.number_field :user_id, value: current_user.id %>
  </div>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="container">

<%= form_for([@recipe, @comment], url: recipe_comment_path) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :comment_entry, class:"sr-only" %><br>
    <%= f.text_area :comment_entry, class: "form-control", placeholder: "Comment", rows: 5 %>
  </div>
  <div class="form-group">
    <%= f.label :author, class:"sr-only" %><br>
    <%= f.text_field :author, class: "form-control", placeholder: "author" %>
  </div>
  <div class="field cant-see-me">
    <%= f.number_field :recipe_id, value: @recipe.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<html>
<head>
  <title>Recipes</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Architects+Daughter" rel="stylesheet">
</head>

<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <span class="navbar-brand"><font color="red">Chef</font><font color="black">2</font><font color="blue">Chef</font></span>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "All Recipes", root_path %></li>
          <li><%= link_to "Your Recipes", your_recipes_path %></li>
          <li><%= link_to "Post a Recipe", new_recipe_path %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

    <%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(recipe) do |f| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <br>

<div class="form-group">
    <%= f.label :category %>
    <%= f.text_field :category, class: "form-control", placeholder: "(i.e. Mexican, American, Chinese, etc.)" %>
  </div>
  <br>

  <div class="form-group">
    <%= f.label :ingredients %>
    <%= f.text_area :ingredients, class: "form-control", rows:4 %>
  </div>
  <br>

  <div class="form-group">
    <%= f.label :directions %>
    <%= f.text_area :directions, class: "form-control", rows:4 %>
  </div>
  <br>

  <div class="form-group">
    <%= f.label :notes %>
    <%= f.text_area :notes, class: "form-control", rows:4 %>
  </div>
  <br>

  <div class="field form-group">
    <%= f.label "Photo" %><br>
    <%= f.file_field :avatar %>
  </div>


  <div class="cant-see-me">
    <%= f.number_field :user_id, value: current_user.id %>
  </div> 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<div class="container">


<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

</div>

app/views/recipes/index.html.erb
<div class="hero-unit">
  <div>
    <br><br><br><br><br>
    <center><h1>Make Something Delicious</h1></center>
    <center><h2>Find a recipe on almost anything you could want and become the chef you've always wanted to be.</h2></center>
  </div>
</div>

<div class="container">
  
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

  <div class="row">
    <% @recipes.each do |recipe| %>
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
        <h4><%= link_to recipe.title, recipe %></h4>

        </div>
        
        <div class="panel-body">
        <% if recipe.avatar_file_name != nil %>
          <%= image_tag recipe.avatar.url(:medium), class: "img-rounded" %></p>
        <% end %>
         By <%= link_to recipe.user.username, user_recipes_path(id: recipe.user.id) %> <br>
          <i>Posted <%= recipe.created_at.strftime('%m/%d/%Y at %I:%M%p') %></i>
          <p>Ingredients: <%= recipe.ingredients[0..250] %>...[<%= link_to "Read More", recipe %>]</p>
        </div>
        <% if current_user.id == recipe.user.id %>
        <div class="panel-footer">
          <%= link_to "Edit", edit_recipe_path(recipe), class: "btn btn-warning" %>
          <%= link_to "Delete", recipe, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
        </div>
        <% end %>
      </div>
    </div>
    <% end %>
    </div>
    <%= link_to 'New Recipe', new_recipe_path, class: "btn btn-default" %>
  </div>
 

<br>
</div>

app/views/recipes/new.html.erb
<div class="container">


<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path, class: "btn btn-primary" %>

</div>

app/views/recipes/show.html.erb
<div class="container">
  
<p id="notice"><%= notice %></p>

  <div class="panel panel-primary">
    <div class="panel-heading">
      <%= @recipe.title %>
    </div>
    <div class="panel-body">
      <p>
        <% if @recipe.avatar_file_name != nil %>
          <%= image_tag @recipe.avatar.url(:medium), class: "img-responsive" %></p>
        <% end %>
      <p>Posted by: <%= link_to @recipe.user.username, user_recipes_path(id: @recipe.user.id)%></p>
      <p>Category: <%= @recipe.category %></p>
      <p>Recipe notes: <%= @recipe.notes %></p>
      
      <p>Ingredients: <%= @recipe.ingredients %></p>
      <p>Directions: <%= @recipe.directions %></p>
      
    </div>
    <% if current_user.id == @recipe.user.id %>
    <div class="panel-footer">
        <%= link_to "Edit", edit_recipe_path(@recipe), class: "btn btn-warning" %>
        <%= link_to "Delete", @recipe, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
    </div>
    <% end %>
  </div>

<div class="panel-body"><%= render "comments/form" %></div>

  <div class="panel panel-default">
    <div class="panel-header">
      
      <h4>Comments</h4>
    </div>
    <% @recipe.comments.each do |comment| %>
      <div class="panel-body">

        <div id="rated">
          <strong>Rating:</strong>
          <%= "#{comment.rating}".to_i.times do |rank| %>
            <span class="glyphicon glyphicon-star"></span>
          <% end %>
        <div>

        <p><%= comment.comment_entry %></p>
        <p>Created on <%= comment.created_at.strftime("%m/%d/%y") %> at <%= comment.created_at.strftime("%I:%M %p") %></p>
        
      </div>

        <% if current_user.id == @recipe.user.id %>
        <div class="panel-footer">
          <%= link_to "Edit Comment", edit_recipe_comment_path(@recipe, comment) %> |
          <%= link_to "Delete", [comment.recipe, comment], method: :delete, data: {confirm: 'Are you sure?'} %>
        </div>
        <% end %>

       </div>
    <% end %>
  </div>

<%= link_to 'Back', recipes_path, class: "btn btn-primary" %>

</div>

app/views/recipes/user_recipes.html.erb
<div class="container">

<h1><%= @user.username %>'s Page</h1>

<p><strong>Name:</strong> <%= @user.name %></p>

<p><strong>Birthday:</strong><%= @user.birthday.strftime('%m/%d/%Y') %></p>

<div class="row">
	<% @user.recipes.each do |recipe| %>
	<div class="col-md-12">
		<div class="panel panel-success">
		<div class="panel-heading">
			<%= link_to recipe.title, recipe %>
		</div>

		<div class="panel-body">
			by <%= recipe.user.username %>
				<p><span class="posted-at">posted at: <%= recipe.created_at.strftime('%m/%d/%Y at %I:%M%p') %></span></p>
				<p><%= recipe.ingredients[0..250] %>...[<%= link_to "Read More", recipe %>]</p><br>

		</div>

     <% if current_user.id == recipe.user.id %>
        <div class="panel-footer">
          <%= link_to "Edit", edit_recipe_path(recipe), class: "btn btn-warning" %>
          <%= link_to "Delete", recipe, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
        </div>
        <% end %>

		</div>
	</div>
	<% end %>
</div>

<br>

</div>

app/views/recipes/your_recipes.html.erb
<div class="container">

<h1>Your Recipes</h1>

  <div class="row">
    <% current_user.recipes.each do |recipe| %>
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
        <%= link_to recipe.title, recipe %>

        </div>
        
        <div class="panel-body">
         By <%= recipe.user.username %> <br>
          <i>Posted <%= recipe.created_at.strftime('%m/%d/%Y at %I:%M%p') %></i>
          <p><%= recipe.ingredients[0..250] %>...[<%= link_to "Read More", recipe %>]</p>
        </div>

        <% if current_user.id == recipe.user.id %>
        <div class="panel-footer">
          <%= link_to "Edit", edit_recipe_path(recipe), class: "btn btn-warning" %>
          <%= link_to "Delete", recipe, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
        </div>
        <% end %>
    
      </div>
    </div>
    <% end %>
  </div>
  
  
</div>